# Generated by Django 4.1.7 on 2023-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_eshop', '0002_sale_numofpieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='mainImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='secondImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
