# Generated by Django 4.1.7 on 2023-06-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_eshop', '0003_accessory_datetime_accessory_mainimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('gjerdani', 'ѓердани'), ('obetki', 'обетки'), ('broshovi', 'брошови'), ('prsteni', 'прстени'), ('kosa', 'додатоци за во коса'), ('alki', 'алки')], max_length=8),
        ),
        migrations.CreateModel(
            name='History_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfPieces', models.IntegerField(blank=True, null=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unique_eshop.accessory')),
                ('shoppingCart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unique_eshop.shoppingcart')),
            ],
        ),
    ]
