# Generated by Django 4.1.7 on 2023-06-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_eshop', '0004_alter_accessory_category_history_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfPieces', models.IntegerField(blank=True, null=True)),
                ('successfully_paid', models.BooleanField(default=False, null=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unique_eshop.accessory')),
                ('shoppingCart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unique_eshop.shoppingcart')),
            ],
        ),
        migrations.DeleteModel(
            name='History_Sale',
        ),
    ]
